# Generated by Django 5.2.4 on 2025-10-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelcategory',
            options={'ordering': ['name'], 'verbose_name': 'Channel Category', 'verbose_name_plural': 'Channel Categories'},
        ),
        migrations.AlterModelOptions(
            name='synclogs',
            options={'ordering': ['timestamp'], 'verbose_name': 'Sync Log', 'verbose_name_plural': 'Sync Logs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='channelwhitelist',
            name='channel_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='channelwhitelist',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='synclogs',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
